name: Scheduled Tag Build

on:
  schedule:
    - cron: "0 0 * * *" # 每天 00:00 运行
  workflow_dispatch:

jobs:
  check_latest_tag:
    name: Check for latest tag
    runs-on: ubuntu-latest
    outputs:
      build_ref: ${{ steps.check.outputs.build_ref }}
      release_tag: ${{ steps.check.outputs.release_tag }}
      release_body: ${{ steps.check.outputs.release_body }}
      should_build: ${{ steps.check.outputs.should_build }}
    steps:
      - name: Check latest tag
        id: check
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # 获取最新的 tag
          LATEST_TAG=$(gh api repos/${{ github.repository }}/tags --jq '.[0].name')
          echo "Latest tag: $LATEST_TAG"

          # 确保 tag 存在
          if [ -z "$LATEST_TAG" ]; then
            echo "No tags found, skipping build"
            echo "should_build=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          # 设置输出变量
          echo "build_ref=$LATEST_TAG" >> $GITHUB_OUTPUT
          echo "release_tag=$LATEST_TAG" >> $GITHUB_OUTPUT
          echo "should_build=true" >> $GITHUB_OUTPUT

          # 提取 release body
          RELEASE_BODY=$(echo "$LATEST_RELEASE" | jq -r '.body')
          echo "release_body<<EOF" >> $GITHUB_OUTPUT
          echo "$RELEASE_BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  trigger_build:
    name: Build
    needs: check_latest_tag
    if: ${{ needs.check_latest_tag.outputs.should_build == 'true' }}
    uses: ./.github/workflows/build.yml
    with:
      ref: ${{ needs.check_latest_tag.outputs.build_ref }}

  trigger_release:
    name: Release
    needs: [check_latest_tag, trigger_build]
    uses: ./.github/workflows/release.yml
    with:
      is_prerelease: false
      release_tag: ${{ needs.check_latest_tag.outputs.release_tag }}
      release_body: ${{ needs.check_latest_tag.outputs.release_body }}
    permissions:
      contents: write
